import Banner from '@/components/Banner'
import Breadcrumb from '@/components/layout/Breadcrumb'
import ProductCard from '@/components/Cards/ProductCard'
import Head from 'next/head'

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Banner/>
      <div className='my-2 bg-light'>
        <h4 className='text-center p-2 text-uppercase'>products</h4>
      </div>
      <div  className='row'>
      { products && products.map((item)=>{
        return(
          <div  key = {item.id} className='col-md-4'>
          <div className='mt-4'>
          <ProductCard product={item}/>
          </div>
      </div>
        )
       })}
      </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {

  // const response=await fetch('https://dummyjson.com/products');
  // const result =await response.json();
  // return {
  //   props: {}, // will be passed to the page component as props
  // }
    let products =[];

  try {
    const response=await fetch('https://dummyjson.com/products');
   const result =await response.json();
   products = result.products;
    
  } catch (error) {
    console.error(error);
    return {notFound:true}
    
  }
  return {
      props: {
        products
      }, // will be passed to the page component as props
    }

}